dir_assets:
  'examples/compose/':
    files: ['docker-compose.yml']
    template: 'compose/docker-compose.yaml.tmpl'
#  'examples/helm/':
#    files: ['Values.yaml', 'Chart.yaml']
#    template: 'helm/chart_values.yaml.tmpl'
#  'examples/helm/templates/':
#    files:
#    template:
#  'examples/k8s/templates/':
#    files: ['deployment.yaml']
#    template: 'k8s/deployment.yaml.tmpl'
#  'dashboards/overview/':
#    files: ['main.tf']
#    template: 'dashboards/main.tf.head.tmpl'
#  'alerts/mem/':
#    files:
#    template: 'alerts/alerts.tmpl'
#  'images/':
#    files: ['dashboards-overview.png']
#    template: 'images/images.tmpl'
