version: '3.8'

services:
  pure-fa-om-exporter:
    image: quay.io/purestorage/pure-fa-om-exporter:latest
    command: 
      - '--port=9490'
    ports:
      - 9490:9490
    restart: on-failure
    depends_on: 
      - otel-collector

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.81.0
    hostname: otel-collector
    restart: always
    command: [ "--config=/conf/collector.yaml" ]
    volumes:
      - ./collector.yaml:/conf/collector.yaml:rw
    environment:
      LS_ACCESS_TOKEN: "${LS_ACCESS_TOKEN}"
