version: '3.7'
services:
  wildfly:
    container_name: wildfly
    build: 
      context: .
      args:
          JAVA_OPTS_1: '-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=9404:/opt/jmx_exporter/jmx_exporter.yaml '
          LOGMANAGER: '-Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dorg.jboss.logging.Logger.pluginClass=org.jboss.logging.logmanager.LoggerPluginImpl -Dsun.util.logging.disableCallerCheck=true '
          LOGMANAGER_JAR: '/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.18.Final.jar:'
          WILDLFY_COMMON_JAR: '/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.5.4.Final.jar'
    ports:
      - "8080:8080"
      - "9990:9990"
      - "9404:9404"
    volumes:
      - ./jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx_exporter/jmx_exporter.yaml:/opt/jmx_exporter/jmx_exporter.yaml
      - ./ping/deployments:/opt/jboss/wildfly/standalone/deployments
    networks:
      - integrations

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.81.0
    hostname: otel-collector
    restart: always
    command: [ "--config=/conf/collector.yaml" ]
    volumes:
      - ./collector.yaml:/conf/collector.yaml:rw
    environment:
      LS_ACCESS_TOKEN: "${LS_ACCESS_TOKEN}"
    networks:
        - integrations

networks:
    integrations:
