version: '2'
services:
    kong-gateway:
        image: kong/kong-gateway:3.4.1.1
        container_name: kong-gateway
        environment:
          - KONG_DATABASE=off
          - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
          - KONG_ADMIN_LISTEN=0.0.0.0:8001
          - KONG_ADMIN_GUI_URL=http://localhost:8002
          - KONG_PORTAL_GUI_HOST=http://localhost:8003/default
          - KONG_PORTAL="on kong reload exit"
        ports:
          - '8000:8000'
          - '8001:8001'
          - '8002:8002'
          - '8443:8443'
          - '8444:8444'
          - '8445:8445'
          - '8003:8003'
          - '8004:8004'
          - '8100:8100'
        volumes:
          - ./kong.conf:/etc/kong/kong.conf:rw
          - ./kong.yml:/etc/kong/kong.yml:rw
          - ./logs/kong:/var/log/kong
    client:
        build: ./app
          # container_name: client
        environment:
          - DESTINATION_HOST=kong-gateway
          - COLLECTOR_HOST=otel-collector
        depends_on:
          - kong-gateway
          - otel-collector
        stop_grace_period: 1s
    otel-collector:
        container_name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.88.0
        command: ["--config=/conf/collector.yml"]
        environment:
          LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
        ports:
          - "4317:4317"
          - "4318:4318"
        volumes:
            - ./collector.yml:/conf/collector.yml:rw
            - ./logs/kong:/var/log/kong
volumes:
  kong-logs:
