apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: otel-collector
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.84.0
        imagePullPolicy: IfNotPresent
        command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        ports:
        - containerPort: 4317
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-access-token
              key: access_token
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
      volumes:
      - configMap:
          defaultMode: 420
          items:
            - key: otel-collector-conf
              path: otel-collector-config.yaml
          name: otel-collector-conf
        name: otel-collector-config-vol
