apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
  type: LoadBalancer
