apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: sleep-logging
  namespace: go-istio-demo
spec:
  selector:
    matchLabels:
      app: sleep
  accessLogging:
    - providers:
        - name: otel-logging
  tracing:
    - providers:
        - name: otel-tracing
