version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_VERSION:-0.81.0}
    hostname: otel-collector
    restart: always
    command: [ "--config=/conf/collector.yaml" ]
    volumes:
      - ./collector.yaml:/conf/collector.yaml:rw
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}

  neo4j:
    image: neo4j:5.11.0-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
      - "2004:2004"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - neo4j-data:/data
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_AUTH: none
      NEO4J_EDITION: "enterprise"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

volumes:
  neo4j-data:
    driver: local
