---
apiVersion: v1
kind: Service
metadata:
  name: kong-metrics
  namespace: kong
spec:
  ports:
  - name: metrics
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: proxy-kong
