name: Validate PR

on:
  pull_request:
    paths:
    - '**.tf'
    - '**.go'

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform FMT Check
      run: |
        terraform init
        terraform fmt -check

  terraform-lint:
    name: Terraform Lint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tflint
      run: |
        wget https://github.com/terraform-linters/tflint/releases/download/v0.31.0/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        sudo mv tflint /usr/local/bin/
    - name: Run tflint
      run: tflint

  go-lint:
    name: Go Best Practices Lint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Install golangci-lint
      run: |
        wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.42.0
    - name: Run golangci-lint
      run: ./bin/golangci-lint run
